modLoader="lowcodefml"
loaderVersion= "[40,)"

license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/Amronos/create-addon-compatibility/issues"
showAsResourcePack=false

[[mods]]
modId="create_addon_compatibility"
version="0.1.0a"
displayName="Create: Addon Compatibility"
#updateJSONURL=""
displayURL="https://modrinth.com/mods/create-addon-compatibility"
#logoFile=""
#credits=""
authors="Amronos"
description="Adds compatibility between create addons."


[dependencies]
[[dependencies.create_addon_compatibility]]
modId = "forge"
mandatory = false
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_addon_compatibility]]
modId = "neoforge"
mandatory = false
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_addon_compatibility]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_addon_compatibility]]
  modId="almostunified"
  mandatory=true
  versionRange="[1.20.1-0.9.2,)"
  ordering="AFTER"
  side="BOTH"
  referralUrl="https://modrinth.com/mod/almost-unified"

[[dependencies.create_addon_compatibility]]
  modId="create"
  mandatory=true
  versionRange="[0.5.1.e,)"
  ordering="AFTER"
  side="BOTH"
  referralUrl="https://modrinth.com/mod/create"

[[dependencies.create_addon_compatibility]]
  modId="destroy"
  mandatory=false
  versionRange="[0.8,)"
  ordering="AFTER"
  side="BOTH"
  referralUrl="https://modrinth.com/mod/destroy"

[[dependencies.create_addon_compatibility]]
  modId="createaddition"
  mandatory=false
  versionRange="[1.20.1-1.2.2,)"
  ordering="AFTER"
  side="BOTH"
  referralUrl="https://modrinth.com/mod/createaddition"

[[dependencies.create_addon_compatibility]]
  modId="createdieselgenerators"
  mandatory=false
  versionRange="[1.20.1-1.2h,)"
  ordering="AFTER"
  side="BOTH"
  referralUrl="https://modrinth.com/mod/create-diesel-generators"

[[dependencies.create_addon_compatibility]]
  modId="tfmg"
  mandatory=false
  versionRange="[0.8.0b,)"
  ordering="AFTER"
  side="BOTH"
  referralUrl="https://modrinth.com/mod/create-tfmg"